import Head from "next/head";

import Image from "next/image";

import Footer from "../components/Footer";

import styles from "../styles/Home.module.css";

export default function Home() {
    return (
        <>
            <Head>
                <title>Next Website Template</title>
                <meta name="description" content="Generated by create next app" />
                {/*<link rel="icon" href="/favicon.ico" />*/}
            </Head>
            <header>
              <h1>Next Website Template</h1>
            </header>
            <main>
              <section>
                <h2>First Read</h2>
                <span>Underliner</span>
                <article>
                  <h4>Article head</h4>
                  <p>Lorup ipsum donovou gerade.</p>
                </article>
                <article>
                  <h4>Article Two</h4>
                  <p>Lorup ipsum donovou gerade II.</p>
                </article>
              </section>
            </main>
            <aside>
              
            </aside>
            <Footer />
        </>
    )

}
